-- MySQL Script generated by MySQL Workbench
-- 04/25/15 20:49:38
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbOTB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbOTB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbOTB` ;

-- -----------------------------------------------------
-- Table `dbOTB`.`Configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Configuracion` (
  `pk_Configuracion` INT NOT NULL AUTO_INCREMENT,
  `vch_confLogoOTB` VARCHAR(500) NULL,
  `vch_confTituloSoftware` VARCHAR(500) NULL,
  `vch_confDetalleSoftware` VARCHAR(250) NULL,
  `vch_confDescripcionSoftware` VARCHAR(500) NULL,
  `int_confFuenteSizeTituloSoft` INT NULL,
  `int_confFuenteSizeDetalleSoft` INT NULL,
  `int_confFuenteSizeDescripSoft` INT NULL,
  `vch_confLenguaje` VARCHAR(500) NULL,
  `vch_confTemaSkin` VARCHAR(500) NULL,
  `vch_confColorIngresos` VARCHAR(500) NULL,
  `vch_confColorEgresos` VARCHAR(500) NULL,
  `vch_confImagenPDF` VARCHAR(500) NULL,
  `int_confFuenteSizeTitulos` INT NULL,
  `int_confFuenteSizeTitulosCampos` INT NULL,
  `int_confFuenteSizeDatos` INT NULL,
  `int_confFuenteSizeBTN` INT NULL,
  `dat_confFechaCopyRight` DATE NULL,
  `vch_confNombreDevSoft` VARCHAR(500) NULL,
  `vch_confLogoDevSoft` VARCHAR(500) NULL,
  PRIMARY KEY (`pk_Configuracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Privilegio` (
  `pk_Privilegio` INT NOT NULL AUTO_INCREMENT,
  `vch_privNombre` VARCHAR(500) NULL,
  `vch_privPath` VARCHAR(500) NULL,
  `bol_privCliente` TINYINT(1) NULL,
  `bol_privAdmin` TINYINT(1) NULL,
  `vch_privEstado` VARCHAR(1) NULL,
  PRIMARY KEY (`pk_Privilegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Rol` (
  `pk_Rol` INT NOT NULL AUTO_INCREMENT,
  `vch_rolNombre` VARCHAR(500) NULL,
  `vch_rolEstado` VARCHAR(1) NULL,
  PRIMARY KEY (`pk_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Asignado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Asignado` (
  `pk_Asignado` INT NOT NULL AUTO_INCREMENT,
  `int_asigPrivilegioAsignado` INT NULL,
  `fk_Asignado_Privilegio` INT NOT NULL,
  `fk_Asignado_Rol` INT NOT NULL,
  PRIMARY KEY (`pk_Asignado`),
  INDEX `fk_Asignado_Privilegio_idx` (`fk_Asignado_Privilegio` ASC),
  INDEX `fk_Asignado_Rol1_idx` (`fk_Asignado_Rol` ASC),
  CONSTRAINT `fk_Asignado_Privilegio`
    FOREIGN KEY (`fk_Asignado_Privilegio`)
    REFERENCES `dbOTB`.`Privilegio` (`pk_Privilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignado_Rol1`
    FOREIGN KEY (`fk_Asignado_Rol`)
    REFERENCES `dbOTB`.`Rol` (`pk_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`OTB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`OTB` (
  `pk_OTB` INT NOT NULL AUTO_INCREMENT,
  `vch_otbNombre` VARCHAR(250) NULL,
  `vch_otbNombreDistrito` VARCHAR(250) NULL,
  `vch_otbNombreMunicipio` VARCHAR(250) NULL,
  `vch_otbEstado` VARCHAR(1) NULL,
  PRIMARY KEY (`pk_OTB`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Usuario` (
  `pk_Usuario` INT NOT NULL AUTO_INCREMENT,
  `vch_usuaTipoUsuario` VARCHAR(250) NULL,
  `vch_usuaUsername` VARCHAR(250) NULL,
  `vch_usuaNombre` VARCHAR(250) NULL,
  `vch_usuaApp` VARCHAR(250) NULL,
  `vch_usuaApm` VARCHAR(250) NULL,
  `vch_usuaSexo` VARCHAR(150) NULL,
  `dat_usuaFechaNacimiento` DATE NULL,
  `vch_usuaCI` VARCHAR(8) NULL,
  `vch_usuaTelefono` VARCHAR(8) NULL,
  `vch_usuaDireccion` VARCHAR(250) NULL,
  `vch_usuaFoto` VARCHAR(500) NULL,
  `vch_usuaEstado` VARCHAR(1) NULL,
  `fk_Usuario_Rol` INT NOT NULL,
  `fk_Usuario_OTB` INT NOT NULL,
  PRIMARY KEY (`pk_Usuario`),
  INDEX `fk_Usuario_Rol1_idx` (`fk_Usuario_Rol` ASC),
  INDEX `fk_Usuario_OTB1_idx` (`fk_Usuario_OTB` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`fk_Usuario_Rol`)
    REFERENCES `dbOTB`.`Rol` (`pk_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_OTB1`
    FOREIGN KEY (`fk_Usuario_OTB`)
    REFERENCES `dbOTB`.`OTB` (`pk_OTB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Anuncio` (
  `pk_Anuncio` INT NOT NULL AUTO_INCREMENT,
  `vch_anunTitulo` VARCHAR(500) NULL,
  `vch_anunContenido` VARCHAR(1000) NULL,
  `vch_anunFoto` VARCHAR(500) NULL,
  `dat_anunFechaInicio` DATE NULL,
  `dat_anunFechaFin` DATE NULL,
  `dat_anunEstado` VARCHAR(1) NULL,
  `fk_Anuncio_Usuario` INT NOT NULL,
  PRIMARY KEY (`pk_Anuncio`),
  INDEX `fk_Anuncio_Usuario1_idx` (`fk_Anuncio_Usuario` ASC),
  CONSTRAINT `fk_Anuncio_Usuario1`
    FOREIGN KEY (`fk_Anuncio_Usuario`)
    REFERENCES `dbOTB`.`Usuario` (`pk_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Manzano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Manzano` (
  `pk_Manzano` INT NOT NULL AUTO_INCREMENT,
  `int_manzNumeroManzano` INT NULL,
  `vch_manzDescripcion` VARCHAR(500) NULL,
  `vch_manzEstado` VARCHAR(1) NULL,
  `fk_Manzano_OTB` INT NOT NULL,
  PRIMARY KEY (`pk_Manzano`),
  INDEX `fk_Manzano_OTB1_idx` (`fk_Manzano_OTB` ASC),
  CONSTRAINT `fk_Manzano_OTB1`
    FOREIGN KEY (`fk_Manzano_OTB`)
    REFERENCES `dbOTB`.`OTB` (`pk_OTB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Propiedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Propiedad` (
  `pk_Propiedad` INT NOT NULL AUTO_INCREMENT,
  `vch_propTipo` VARCHAR(250) NULL,
  `int_propNumeroLote` INT NULL,
  `vch_propNumeroCasa` VARCHAR(250) NULL,
  `vch_propEstado` VARCHAR(1) NULL,
  `fk_Propiedad_Manzano` INT NOT NULL,
  `fk_Propiedad_Usuario` INT NOT NULL,
  PRIMARY KEY (`pk_Propiedad`),
  INDEX `fk_Propiedad_Manzano1_idx` (`fk_Propiedad_Manzano` ASC),
  INDEX `fk_Propiedad_Usuario1_idx` (`fk_Propiedad_Usuario` ASC),
  CONSTRAINT `fk_Propiedad_Manzano1`
    FOREIGN KEY (`fk_Propiedad_Manzano`)
    REFERENCES `dbOTB`.`Manzano` (`pk_Manzano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propiedad_Usuario1`
    FOREIGN KEY (`fk_Propiedad_Usuario`)
    REFERENCES `dbOTB`.`Usuario` (`pk_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Gestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Gestion` (
  `pk_Gestion` INT NOT NULL AUTO_INCREMENT,
  `vch_gestNombrePeriocidad` VARCHAR(250) NULL,
  `vch_gestDescripcion` VARCHAR(500) NULL,
  `vch_gestEstado` VARCHAR(1) NULL,
  PRIMARY KEY (`pk_Gestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`Aporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`Aporte` (
  `pk_Aporte` INT NOT NULL AUTO_INCREMENT,
  `dat_aporFecha` DATE NULL,
  `int_aporMonto` INT NULL,
  `vch_aporNotaDetalle` VARCHAR(500) NULL,
  `vch_aporConceptoIngresoEgreso` VARCHAR(500) NULL,
  `vch_aporMetodoPago` VARCHAR(500) NULL,
  `vch_aporTipoestadoIE` VARCHAR(150) NULL,
  `fk_Aporte_Usuario` INT NOT NULL,
  `fk_Aporte_Gestion` INT NOT NULL,
  PRIMARY KEY (`pk_Aporte`),
  INDEX `fk_Aporte_Usuario1_idx` (`fk_Aporte_Usuario` ASC),
  INDEX `fk_Aporte_Gestion1_idx` (`fk_Aporte_Gestion` ASC),
  CONSTRAINT `fk_Aporte_Usuario1`
    FOREIGN KEY (`fk_Aporte_Usuario`)
    REFERENCES `dbOTB`.`Usuario` (`pk_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aporte_Gestion1`
    FOREIGN KEY (`fk_Aporte_Gestion`)
    REFERENCES `dbOTB`.`Gestion` (`pk_Gestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`ConceptoIngresoEgreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`ConceptoIngresoEgreso` (
  `pk_ConceptoIngresoEgreso` INT NOT NULL AUTO_INCREMENT,
  `vch_cieNombre` VARCHAR(250) NULL,
  `vch_cieEstado` VARCHAR(1) NULL,
  `fk_ConceptoIngresoEgreso_Aporte` INT NOT NULL,
  PRIMARY KEY (`pk_ConceptoIngresoEgreso`),
  INDEX `fk_ConceptoIngresoEgreso_Aporte1_idx` (`fk_ConceptoIngresoEgreso_Aporte` ASC),
  CONSTRAINT `fk_ConceptoIngresoEgreso_Aporte1`
    FOREIGN KEY (`fk_ConceptoIngresoEgreso_Aporte`)
    REFERENCES `dbOTB`.`Aporte` (`pk_Aporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOTB`.`NominaAsistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOTB`.`NominaAsistencia` (
  `pk_NominaAsistencia` INT NOT NULL AUTO_INCREMENT,
  `dtt_nomiFecha` DATETIME NULL,
  `vch_nomiNotaDetalle` VARCHAR(500) NULL,
  `bol_nomiAsistenciaEstado` TINYINT(1) NULL,
  `fk_NominaAsistencia_Usuario` INT NOT NULL,
  `fk_NominaAsistencia_Gestion` INT NOT NULL,
  PRIMARY KEY (`pk_NominaAsistencia`),
  INDEX `fk_NominaAsistencia_Usuario1_idx` (`fk_NominaAsistencia_Usuario` ASC),
  INDEX `fk_NominaAsistencia_Gestion1_idx` (`fk_NominaAsistencia_Gestion` ASC),
  CONSTRAINT `fk_NominaAsistencia_Usuario1`
    FOREIGN KEY (`fk_NominaAsistencia_Usuario`)
    REFERENCES `dbOTB`.`Usuario` (`pk_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NominaAsistencia_Gestion1`
    FOREIGN KEY (`fk_NominaAsistencia_Gestion`)
    REFERENCES `dbOTB`.`Gestion` (`pk_Gestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
